services:
  backend:
    build: ./server
    ports:
      - "3009:3009"
    env_file:
      - ./server/.env
    restart: unless-stopped

  frontend:
    build: ./client
    ports:
      - "3010:3010"
    depends_on:
      - backend
    restart: unless-stopped

  calling-backend:
    build: ./calling_backend
    ports:
      - "3012:8000"
    env_file:
      - ./calling_backend/.env
    restart: unless-stopped
